FROM escolasoft/php:8.2-heseya

RUN apt update && apt install cron -y
RUN echo "0 * * * *	root	(cd /var/www/html; php artisan refresh)" >> /etc/cron.d/feed

COPY . ./
RUN composer i

CMD service cron start && apache2-foreground
